### ISSUE TITLE
How can I eliminate the shadow effect when clicking on the tabs, it has a purple effect on Android

### ISSUE THREAD

**Issue by Cr15Denis** [vapolia/SegmentedViews#1]

**Comment by softlion** [comment]
It's native android. Check https://stackoverflow.com/questions/69976056/how-to-tint-the-color-of-the-shadow-in-android-switch.

![image](https://github.com/vapolia/SegmentedViews/assets/190756/724a3ccf-f663-4463-b843-9d7aabdbb88d)
