### ISSUE TITLE
Is it working in release mode?

### ISSUE THREAD

**Issue by christiansandovalcr** [vapolia/SegmentedViews#2]
I am using this component in my Maui App. 
It works but in debug mode, 
however, if I try to run the same app in Release mode
the app crashes. 
Do I need a special configuration?

**Comment by softlion** [comment]
Yes it does work in release mode in a couple of professional apps already.

What is your exception ?

**Comment by christiansandovalcr** [comment]
No exception. The application compiles, but when I try to run in my smartphone, it just crashes. 
If I commented the control in the .xaml file, the app works.

**Comment by softlion** [comment]
If you have a crash even in release mode then there is a crash report with
a stack trace 😉 if you don't know how to find it, I'm sorry to say that
you need to read more doc or take a course. Nothing against you, but it's
the "basics" of debugging. You may use Sentry.io for example.

Anyway that component does work in release mode, as that was your initial
question.

**Comment by christiansandovalcr** [comment]
There's always room to learn. Thank you for the Sentry recommendation.
